config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='courses-list'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('delete/<int:pk>/', views.CourseDeleteView.as_view(), name='course-delete'),
    path('create/', views.CourseCreateView.as_view(), name='course-create'),
    path('update/<int:pk>/', views.CourseUpdateView.as_view(), name='course-update'),
    path('<slug:course_slug>/join/', views.student_enrollment, name='student-enrollment'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.registration_view, name='registration'),
    path('login/', views.login_user_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

templates/partials/messages.html
{% if messages %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

templates/partials/nav.html
{% load static %}
<nav class="navbar navbar-expand-md bg-primary" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.svg' %}" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'courses:courses-list' %}">Courses</a>
                </li>

                {% if user.is_authenticated %}
                    {% if user.is_instructor %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'courses:course-create' %}">New Course</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">{{ user.fullname }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
                    </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'users:registration' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>