config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='courses-list'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('delete/<int:pk>/', views.CourseDeleteView.as_view(), name='course-delete'),
    path('create/', views.CourseCreateView.as_view(), name='course-create'),
    path('update/<int:pk>/', views.CourseUpdateView.as_view(), name='course-update'),
    path('<slug:course_slug>/join/', views.student_enrollment, name='student-enrollment'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

courses/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.text import slugify


class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Course(models.Model):
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='courses_creator')
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE, related_name='courses')
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(get_user_model(), related_name='courses_students')
    course_image = models.ImageField(upload_to='courses/')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Module(models.Model):
    course = models.ForeignKey('Course', on_delete=models.CASCADE, related_name='modules')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, default='')

    def __str__(self):
        return self.title


class Content(models.Model):
    module = models.ForeignKey('Module', related_name='contents', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={
        'model__in': ('text', 'video', 'image', 'file')
    })

    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')


class ItemBase(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='%(class)s_related')
    title = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Text(ItemBase):
    content = models.TextField()


class Video(ItemBase):
    content = models.URLField()


class File(ItemBase):
    content = models.FileField(upload_to='files/')


class Image(ItemBase):
    content = models.ImageField(upload_to='images/')

courses/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from . import models
from .permissions import OwnerRequiredMixin


class CourseListView(ListView):
    model = models.Course
    template_name = 'courses/courses_list.html'
    context_object_name = 'courses'


class CourseDetailView(DetailView):
    model = models.Course
    template_name = 'courses/course_details.html'
    context_object_name = 'course'


class CourseDeleteView(LoginRequiredMixin, OwnerRequiredMixin, DeleteView):
    model = models.Course
    success_url = reverse_lazy('courses:courses-list')
    login_url = reverse_lazy('users:login')
    template_name = 'courses/course_delete.html'
    context_object_name = 'course'


class CourseCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Course
    fields = ('title', 'slug', 'subject', 'overview', 'course_image')
    template_name = 'courses/course_create.html'
    success_url = reverse_lazy('courses:courses-list')
    login_url = reverse_lazy('users:login')
    permission_required = 'courses.add_course'
    raise_exception = False

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CourseUpdateView(LoginRequiredMixin, OwnerRequiredMixin, UpdateView):
    model = models.Course
    fields = ('title', 'slug', 'subject', 'overview')
    template_name = 'courses/course_update.html'
    login_url = reverse_lazy('users:login')
    context_object_name = 'course'

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse('courses:course-detail', kwargs={'pk': pk})


@login_required
def student_enrollment(request, course_slug):
    if request.method == 'POST':
        try:
            course = models.Course.objects.get(slug=course_slug)
            if course is not None:
                students = course.students.all()
                if request.user not in students:
                    course.students.add(request.user)
                    messages.add_message(request, messages.SUCCESS, 'You enrolled in this course 😎')
                    return redirect(reverse_lazy('courses:courses-list'))
                else:
                    messages.add_message(request, messages.WARNING, 'You already enrolled in this course')
                    return redirect(reverse_lazy('courses:courses-list'))
            else:
                messages.add_message(request, messages.WARNING, 'Course does not exist')
                return redirect(reverse_lazy('courses:courses-list'))

        except ObjectDoesNotExist:
            messages.add_message(request, messages.ERROR, 'Course not found')
            return redirect(reverse_lazy('courses:courses-list'))

courses/templates/courses/course_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block container %}
    <h1>Create course</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-warning">Add course</button>
    </form>
{% endblock %}

courses/templates/courses/course_delete.html
{% extends 'base.html' %}

{% block container %}
    <form action="{% url 'courses:course-delete' pk=course.pk %}" method="post">
        {% csrf_token %}
        <h2 class="text-center mt-3">Are you sure you want to delete <b>{{ course }}</b></h2>
        <button class="btn btn-success float-right btn-lg mb-3 mt-0" type="submit">Confirm</button>
    </form>
{% endblock %}

courses/templates/courses/course_details.html
{% extends 'base.html' %}

{% block container %}
    <div class="row">
        <div class="col-md-3 col-md-offset-2">
            <img src="{{ course.course_image.url }}" alt="{{ course.title }}" class="img-thumbnail">
        </div>
        <div class="col-md-9">
            <h1>{{ course.title }}</h1>
            <p><i>Created by: {{ course.owner.fullname }} at {{ course.created|date }}</i></p>
            <p class="lead my-3">{{ course.overview }}</p>
            {% if user.is_authenticated %}
                {% if course.owner.id == request.user.id %}
                    <a href="{% url 'courses:course-update' pk=course.pk %}" class="btn btn-danger">Edit Course</a>
                    <a href="{% url 'courses:course-delete' pk=course.pk %}" class="btn btn-danger">Delete Course</a>
                {% else %}
                    {% if user not in course.students.all %}
                        <form action="{% url 'courses:student-enrollment' course_slug=course.slug %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-warning" value="Take this course">
                        </form>
                    {% else %}
                        <a href="" class="btn btn-success">View Course</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

courses/templates/courses/course_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block container %}
    <h1>Update course: {{ course.title }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
           {% csrf_token %}
           {{ form|crispy }}
           <button type="submit" class="btn btn-warning">Update</button>
    </form>
{% endblock %}

courses/templates/courses/courses_list.html
{% extends 'base.html' %}

{% block container %}
    <div class="row">
        <div class="col">
            <div class="card-group">
                {% for course in courses %}
                    <div class="card mb-3 me-3" style="max-width: 18rem;">
                        <img src="{{ course.course_image.url }}" class="card-img-top" alt="{{ course.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ course.title }}</h5>
                            <p class="card-text">{{ course.overview }}</p>
                            <a href="{% url 'courses:course-detail' pk=course.pk %}" class="btn btn-primary">See
                                course</a>
                        </div>
                    </div>
                {% empty %}
                    <h2>No courses found.</h2>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}